---
title: "2023_week48"
author: "LBE"
date: "2023-11-30"
output: md_document
---

# *Week 48*

## **Setup**

```{r}
library(tidytuesdayR)
library(tidyverse)
library(wesanderson)

tuesdata <- tidytuesdayR::tt_load(2023, week = 48)

who_eps <- tuesdata$drwho_episodes %>% 
  mutate(ID = 1:nrow(who_eps),
         season = replace_na(season_number, 0)) %>% 
  filter(season>0)
  

```

## Explore [start 16:39]

Let's start by looking at a simple number of viewers vs season/episode/year

```{r}
pal <- wes_palette("FantasticFox1", 13, type="continuous")

ggplot(data = who_eps, aes(x=ID, y=uk_viewers, fill=as.factor(season)))+
  geom_smooth(inherit.aes = F,
              aes(x=ID, y=uk_viewers),
               method = "loess", 
               span = 0.9, se=T,  
               linewidth = 0.7,
               linetype = "dotted",
              alpha = 0.1,
              colour = "grey20")+
   geom_area(alpha = 0.5)+
  geom_point(shape = 21, alpha =0.3) +
   geom_smooth(aes(colour = as.factor(season)),
               method = "loess", 
               span = 0.9, se=F,  
               linewidth = 1.5,
               lineend = "round")+
  # geom_text(label = as.factor(season))+
  labs(y = "Number of U.K. viewers (millions)", x = "")+
  scale_fill_manual(values = pal)+
  scale_colour_manual(values = pal)+
  theme_classic() +
  theme(legend.position = "none",
        panel.grid.major.y = element_line(linewidth = 0.5, colour = "gray30"),
        axis.line = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_text(colour = "grey95", size = 10, family = "arial"),
        axis.title.y = element_text(colour = "grey95", size = 12, family = "arial"),
        axis.ticks.x = element_blank(),
        plot.background = element_rect(fill = "grey20"),
        panel.background = element_rect(fill = "grey20"))
```
hmm, maybe it woudl be interesting to see if an ep

## Final Plot [start hh:mm]

```{r}

```
